### ISSUE TITLE
0.1.10 Broke Something

### ISSUE THREAD

**Issue by FlorianWendelborn** [jitsi/sdp-simulcast#8]
## Error message:

```
Uncaught TypeError: Cannot read property 'ssrcs' of undefined
    at o._restoreSimulcast (https://[...]:10:27147)
    at https://[...]:10:27868
    at https://[...]:10:23587
    at Array.forEach (native)
    at a (https://[...]:10:23549)
    at o.mungeLocalDescription (https://[...]:10:27800)
    at t.S.patchLocalSDP (https://[...]:5:23997)
    at https://[...]:5:24483
```

### Snippet 1

```javascript
this.simulcast = new Simulcast({
	"numOfLayers": 2
})
```

### Snippet 2

```javascript
/**
 * @description patch local SDP
 * @returns {String} patched local description
 */
patchLocalSDP = sdp => {
	this.debug('patchLocalSDP', sdp)

	const simulcastSDP = this.simulcast.mungeLocalDescription({type: 'offer', sdp}).sdp

	return this.patchSDP(simulcastSDP)
}

/**
 * @description patch remote SDP
 * @returns {String} patched remote description
 */
patchRemoteSDP = sdp => {
	this.debug('patchRemoteSDP', sdp)

	const simulcastSDP = this.simulcast.mungeRemoteDescription({type: 'answer', sdp}).sdp

	return this.patchSDP(simulcastSDP)
}
```

## Additional Information

No error is thrown in v0.1.7.

**Comment by bbaldino** [comment]
Thanks for reporting this...I just changed a bunch of things so guess I broke something.  Will take a look tomorrow.  Do you happen to have a repro case for it so I can use that to make sure it gets fixed?

**Comment by FlorianWendelborn** [comment]
Unfortunately not, because the source is closed. :(

I'm ready to help with testing it though, so just tell me when you think you have the issue or need further specific information.

**Comment by bbaldino** [comment]
@dodekeract do you have any info on when (which scenario) or how this issue occurred?  For an answer to not have any ssrcs, i would expect that it would be recvonly (and never reach _restoreSimulcast like it did in your stack trace).  But for your exception to occur, it would have to be sendrecv (or, at least, not recvonly or inactive) but not have any ssrcs in the sdp, so I'm just wondering what the use case is for that to happen.  What's the library you're using that is using sdp-simulcast?

**Comment by FlorianWendelborn** [comment]
It's a custom library written for @attach-live. We're using a quite customized version of jitsi that only includes the parts we need.

Everything browser-side except `sdp-simulcast` is directly under my control. If it helps you I can provide the whole (or censored parts, not 100% sure yet) SDP exchange process. Note that I'm also not *100%* sure if we're using `sdp-simulcast` correctly, as we have not yet actively investigated the streams.

Issue seems to occur directly after upgrading, as soon as `sdp-simulcast` is trying to manipulate the SDP, at least that's how it looks on my side.

Would an SDP dump help you? If yes - the whole exchange process or just the SDP passed to `sdp-simulcast`?

**Comment by bbaldino** [comment]
@dodekeract thanks for the context.  I'm trying to better understand the scenario where sdp-simulcast gets passed an sdp with a non-recvonly video mline but no existing video ssrcs so I can figure out if that should be treated as an error scenario or if it should inject all N video layers.

Actually I just took a look at the old behavior (before my changes) and the library used to detect this and do nothing (if no existing sources are present, just return the sdp as-is).  So I'll fix things to restore that behavior.

**Comment by FlorianWendelborn** [comment]
@bbaldino interesting, I'll make an issue on our code that we should triple check if simulcast actually works.

**Comment by FlorianWendelborn** [comment]
Closing since I can no longer reproduce this issue.
